sudo: false
language: scala
scala:
  - 2.11.7
  - 2.10.6
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find "$HOME/.sbt" -name "*.lock" -print -delete
  - find "$HOME/.ivy2" -name "ivydata-*.properties" -print -delete
